FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir flask requests

COPY load_balancer.py ./

EXPOSE 8080
# Uncomment
CMD ["python", "load_balancer.py"]
